[package]
name = "vyxen"
version = "0.2.1"
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.87.0"
homepage = "https://glowydeveloper.github.io/Vyxen/"
repository = "https://github.com/GlowyDeveloper/Vyxen"
keywords = ["game", "engine", "gamedev", "gui"]
categories = ["gui", "game-development", "game-engines", "graphics"]
description = "A Godot-style game engine library written in Rust."
readme = "README.md"

[lib]
name = "vyxen"
crate-type = ["lib", "cdylib", "staticlib"]

[workspace]
resolver = "3"
members = [
    ".",
    "testbed",
    "examples/ball-pit",
    "examples/counter",
    "examples/readme",
    "examples/radio",
]

[dependencies]
winit = { version = "0.30.13", default-features = false, features = ["rwh_06"] }
bytemuck = { version = "1.25.2", features = ["derive"] }

skrifa = "0.47.0"
zeno = "0.3.3"

zune-jpeg = { version = "0.5.15", default-features = false }
png = { version = "0.18.1", default-features = false, features = ["zlib-rs"] }

log = "0.4.34"

symphonia = { version = "0.6.1", default-features = false, features = ["ogg", "wav", "aac", "alac", "flac", "mp3", "pcm", "vorbis"] }
cpal = "0.18.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.128"
wasm-bindgen-futures = "0.4.78"
web-time = "1.1.0"
web-sys = { version = "0.3", features = ["Window", "Document", "EventTarget", "AddEventListenerOptions"] }
wgpu = { version = "30.0.1", features = ["webgl", "webgpu"] }
cpal = { version = "0.18.2", features = ["wasm-bindgen"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "1.0.1"
wgpu = "30.0.1"

[target.'cfg(target_os = "linux")'.dependencies]
winit = { version = "0.30.13" }

[target.'cfg(target_os = "android")'.dependencies]
winit = { version = "0.30.13", default-features = false, features = ["android-native-activity"] }
