use winit::keyboard::KeyCode as WinitKeyCode;

/// All keycodes that can be handled.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum KeyCode {
    Backquote = 0,
    Backslash = 1,
    BracketLeft = 2,
    BracketRight,
    Comma,

    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,

    Equal,
    IntlBackslash,

    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,

    Minus,
    Period,
    Quote,
    Semicolon,
    Slash,

    AltLeft,
    AltRight,
    SuperLeft,
    SuperRight,
    ShiftLeft,
    ShiftRight,
    ControlLeft,
    ControlRight,

    Backspace,
    CapsLock,
    ContextMenu,
    Enter,
    Space,
    Tab,

    Convert,
    NonConvert,

    Delete,
    End,
    Help,
    Home,
    Insert,
    PageDown,
    PageUp,

    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,

    NumLock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadBackspace,
    NumpadClear,
    NumpadClearEntry,
    NumpadComma,
    NumpadDecimal,
    NumpadDivide,
    NumpadEnter,
    NumpadEqual,
    NumpadHash,
    NumpadMemoryAdd,
    NumpadMemoryClear,
    NumpadMemoryRecall,
    NumpadMemoryStore,
    NumpadMemorySubtract,
    NumpadMultiply,
    NumpadParenLeft,
    NumpadParenRight,
    NumpadStar,
    NumpadSubtract,

    Escape,
    Fn,
    FnLock,
    PrintScreen,
    ScrollLock,
    Pause,

    BrowserBack,
    BrowserFavorites,
    BrowserForward,
    BrowserHome,
    BrowserRefresh,
    BrowserSearch,
    BrowserStop,

    Eject,

    LaunchApp1,
    LaunchApp2,
    LaunchMail,

    MediaPlayPause,
    MediaSelect,
    MediaStop,
    MediaTrackNext,
    MediaTrackPrevious,

    Power,
    Sleep,
    AudioVolumeDown,
    AudioVolumeMute,
    AudioVolumeUp,
    WakeUp,

    Meta,
    Hyper,
    Turbo,
    Abort,
    Resume,
    Suspend,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    F31,
    F32,
    F33,
    F34,
    F35,

    Unknown,
}

impl From<WinitKeyCode> for KeyCode {
    fn from(value: WinitKeyCode) -> Self {
        match value {
            WinitKeyCode::Backquote => Self::Backquote,
            WinitKeyCode::Backslash => Self::Backslash,
            WinitKeyCode::BracketLeft => Self::BracketLeft,
            WinitKeyCode::BracketRight => Self::BracketRight,
            WinitKeyCode::Comma => Self::Comma,

            WinitKeyCode::Digit0 => Self::Digit0,
            WinitKeyCode::Digit1 => Self::Digit1,
            WinitKeyCode::Digit2 => Self::Digit2,
            WinitKeyCode::Digit3 => Self::Digit3,
            WinitKeyCode::Digit4 => Self::Digit4,
            WinitKeyCode::Digit5 => Self::Digit5,
            WinitKeyCode::Digit6 => Self::Digit6,
            WinitKeyCode::Digit7 => Self::Digit7,
            WinitKeyCode::Digit8 => Self::Digit8,
            WinitKeyCode::Digit9 => Self::Digit9,

            WinitKeyCode::Equal => Self::Equal,
            WinitKeyCode::IntlBackslash => Self::IntlBackslash,

            WinitKeyCode::KeyA => Self::KeyA,
            WinitKeyCode::KeyB => Self::KeyB,
            WinitKeyCode::KeyC => Self::KeyC,
            WinitKeyCode::KeyD => Self::KeyD,
            WinitKeyCode::KeyE => Self::KeyE,
            WinitKeyCode::KeyF => Self::KeyF,
            WinitKeyCode::KeyG => Self::KeyG,
            WinitKeyCode::KeyH => Self::KeyH,
            WinitKeyCode::KeyI => Self::KeyI,
            WinitKeyCode::KeyJ => Self::KeyJ,
            WinitKeyCode::KeyK => Self::KeyK,
            WinitKeyCode::KeyL => Self::KeyL,
            WinitKeyCode::KeyM => Self::KeyM,
            WinitKeyCode::KeyN => Self::KeyN,
            WinitKeyCode::KeyO => Self::KeyO,
            WinitKeyCode::KeyP => Self::KeyP,
            WinitKeyCode::KeyQ => Self::KeyQ,
            WinitKeyCode::KeyR => Self::KeyR,
            WinitKeyCode::KeyS => Self::KeyS,
            WinitKeyCode::KeyT => Self::KeyT,
            WinitKeyCode::KeyU => Self::KeyU,
            WinitKeyCode::KeyV => Self::KeyV,
            WinitKeyCode::KeyW => Self::KeyW,
            WinitKeyCode::KeyX => Self::KeyX,
            WinitKeyCode::KeyY => Self::KeyY,
            WinitKeyCode::KeyZ => Self::KeyZ,

            WinitKeyCode::Minus => Self::Minus,
            WinitKeyCode::Period => Self::Period,
            WinitKeyCode::Quote => Self::Quote,
            WinitKeyCode::Semicolon => Self::Semicolon,
            WinitKeyCode::Slash => Self::Slash,

            WinitKeyCode::AltLeft => Self::AltLeft,
            WinitKeyCode::AltRight => Self::AltRight,
            WinitKeyCode::SuperLeft => Self::SuperLeft,
            WinitKeyCode::SuperRight => Self::SuperRight,
            WinitKeyCode::ShiftLeft => Self::ShiftLeft,
            WinitKeyCode::ShiftRight => Self::ShiftRight,
            WinitKeyCode::ControlLeft => Self::ControlLeft,
            WinitKeyCode::ControlRight => Self::ControlRight,

            WinitKeyCode::Backspace => Self::Backspace,
            WinitKeyCode::CapsLock => Self::CapsLock,
            WinitKeyCode::ContextMenu => Self::ContextMenu,
            WinitKeyCode::Enter => Self::Enter,
            WinitKeyCode::Space => Self::Space,
            WinitKeyCode::Tab => Self::Tab,

            WinitKeyCode::Convert => Self::Convert,
            WinitKeyCode::NonConvert => Self::NonConvert,

            WinitKeyCode::Delete => Self::Delete,
            WinitKeyCode::End => Self::End,
            WinitKeyCode::Help => Self::Help,
            WinitKeyCode::Home => Self::Home,
            WinitKeyCode::Insert => Self::Insert,
            WinitKeyCode::PageDown => Self::PageDown,
            WinitKeyCode::PageUp => Self::PageUp,

            WinitKeyCode::ArrowDown => Self::ArrowDown,
            WinitKeyCode::ArrowLeft => Self::ArrowLeft,
            WinitKeyCode::ArrowRight => Self::ArrowRight,
            WinitKeyCode::ArrowUp => Self::ArrowUp,

            WinitKeyCode::NumLock => Self::NumLock,
            WinitKeyCode::Numpad0 => Self::Numpad0,
            WinitKeyCode::Numpad1 => Self::Numpad1,
            WinitKeyCode::Numpad2 => Self::Numpad2,
            WinitKeyCode::Numpad3 => Self::Numpad3,
            WinitKeyCode::Numpad4 => Self::Numpad4,
            WinitKeyCode::Numpad5 => Self::Numpad5,
            WinitKeyCode::Numpad6 => Self::Numpad6,
            WinitKeyCode::Numpad7 => Self::Numpad7,
            WinitKeyCode::Numpad8 => Self::Numpad8,
            WinitKeyCode::Numpad9 => Self::Numpad9,
            WinitKeyCode::NumpadAdd => Self::NumpadAdd,
            WinitKeyCode::NumpadBackspace => Self::NumpadBackspace,
            WinitKeyCode::NumpadClear => Self::NumpadClear,
            WinitKeyCode::NumpadClearEntry => Self::NumpadClearEntry,
            WinitKeyCode::NumpadComma => Self::NumpadComma,
            WinitKeyCode::NumpadDecimal => Self::NumpadDecimal,
            WinitKeyCode::NumpadDivide => Self::NumpadDivide,
            WinitKeyCode::NumpadEnter => Self::NumpadEnter,
            WinitKeyCode::NumpadEqual => Self::NumpadEqual,
            WinitKeyCode::NumpadHash => Self::NumpadHash,
            WinitKeyCode::NumpadMemoryAdd => Self::NumpadMemoryAdd,
            WinitKeyCode::NumpadMemoryClear => Self::NumpadMemoryClear,
            WinitKeyCode::NumpadMemoryRecall => Self::NumpadMemoryRecall,
            WinitKeyCode::NumpadMemoryStore => Self::NumpadMemoryStore,
            WinitKeyCode::NumpadMemorySubtract => Self::NumpadMemorySubtract,
            WinitKeyCode::NumpadMultiply => Self::NumpadMultiply,
            WinitKeyCode::NumpadParenLeft => Self::NumpadParenLeft,
            WinitKeyCode::NumpadParenRight => Self::NumpadParenRight,
            WinitKeyCode::NumpadStar => Self::NumpadStar,
            WinitKeyCode::NumpadSubtract => Self::NumpadSubtract,

            WinitKeyCode::Escape => Self::Escape,
            WinitKeyCode::Fn => Self::Fn,
            WinitKeyCode::FnLock => Self::FnLock,
            WinitKeyCode::PrintScreen => Self::PrintScreen,
            WinitKeyCode::ScrollLock => Self::ScrollLock,
            WinitKeyCode::Pause => Self::Pause,

            WinitKeyCode::BrowserBack => Self::BrowserBack,
            WinitKeyCode::BrowserFavorites => Self::BrowserFavorites,
            WinitKeyCode::BrowserForward => Self::BrowserForward,
            WinitKeyCode::BrowserHome => Self::BrowserHome,
            WinitKeyCode::BrowserRefresh => Self::BrowserRefresh,
            WinitKeyCode::BrowserSearch => Self::BrowserSearch,
            WinitKeyCode::BrowserStop => Self::BrowserStop,

            WinitKeyCode::Eject => Self::Eject,

            WinitKeyCode::LaunchApp1 => Self::LaunchApp1,
            WinitKeyCode::LaunchApp2 => Self::LaunchApp2,
            WinitKeyCode::LaunchMail => Self::LaunchMail,

            WinitKeyCode::MediaPlayPause => Self::MediaPlayPause,
            WinitKeyCode::MediaSelect => Self::MediaSelect,
            WinitKeyCode::MediaStop => Self::MediaStop,
            WinitKeyCode::MediaTrackNext => Self::MediaTrackNext,
            WinitKeyCode::MediaTrackPrevious => Self::MediaTrackPrevious,

            WinitKeyCode::Power => Self::Power,
            WinitKeyCode::Sleep => Self::Sleep,
            WinitKeyCode::AudioVolumeDown => Self::AudioVolumeDown,
            WinitKeyCode::AudioVolumeMute => Self::AudioVolumeMute,
            WinitKeyCode::AudioVolumeUp => Self::AudioVolumeUp,
            WinitKeyCode::WakeUp => Self::WakeUp,

            WinitKeyCode::Meta => Self::Meta,
            WinitKeyCode::Hyper => Self::Hyper,
            WinitKeyCode::Turbo => Self::Turbo,
            WinitKeyCode::Abort => Self::Abort,
            WinitKeyCode::Resume => Self::Resume,
            WinitKeyCode::Suspend => Self::Suspend,

            WinitKeyCode::F1 => Self::F1,
            WinitKeyCode::F2 => Self::F2,
            WinitKeyCode::F3 => Self::F3,
            WinitKeyCode::F4 => Self::F4,
            WinitKeyCode::F5 => Self::F5,
            WinitKeyCode::F6 => Self::F6,
            WinitKeyCode::F7 => Self::F7,
            WinitKeyCode::F8 => Self::F8,
            WinitKeyCode::F9 => Self::F9,
            WinitKeyCode::F10 => Self::F10,
            WinitKeyCode::F11 => Self::F11,
            WinitKeyCode::F12 => Self::F12,
            WinitKeyCode::F13 => Self::F13,
            WinitKeyCode::F14 => Self::F14,
            WinitKeyCode::F15 => Self::F15,
            WinitKeyCode::F16 => Self::F16,
            WinitKeyCode::F17 => Self::F17,
            WinitKeyCode::F18 => Self::F18,
            WinitKeyCode::F19 => Self::F19,
            WinitKeyCode::F20 => Self::F20,
            WinitKeyCode::F21 => Self::F21,
            WinitKeyCode::F22 => Self::F22,
            WinitKeyCode::F23 => Self::F23,
            WinitKeyCode::F24 => Self::F24,
            WinitKeyCode::F25 => Self::F25,
            WinitKeyCode::F26 => Self::F26,
            WinitKeyCode::F27 => Self::F27,
            WinitKeyCode::F28 => Self::F28,
            WinitKeyCode::F29 => Self::F29,
            WinitKeyCode::F30 => Self::F30,
            WinitKeyCode::F31 => Self::F31,
            WinitKeyCode::F32 => Self::F32,
            WinitKeyCode::F33 => Self::F33,
            WinitKeyCode::F34 => Self::F34,
            WinitKeyCode::F35 => Self::F35,

            _ => Self::Unknown,
        }
    }
}
