[package]
name = "vyxen-resource"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

description = "Resource loading and management for the Vyxen library"
readme = "README.md"

[dependencies]
vyxen-math.workspace = true

image.workspace = true
skrifa.workspace = true
zeno.workspace = true

anyhow.workspace = true